checkout-extension/README.md.liquid
checkout-extension/locales/en.default.json
checkout-extension/locales/fr.json
checkout-extension/package.json.liquid
checkout-extension/shopify.extension.toml.liquid
checkout-extension/src/CheckoutDynamicRender.liquid
checkout-extension/tsconfig.json

Closes https://github.com/Shopify/cli/issues/2199.
Related to https://github.com/Shopify/checkout-web/issues/21910.
Adds the ui-extension template for checkout using the new toml spec and soon to be released `ui-extensions@2023.7`.
This also requires a updated ruby spec in partners to use this new template.

add checkout-extension template

---

product-configuration-extension/README.md.liquid
product-configuration-extension/locales/en.default.json.liquid
product-configuration-extension/locales/fr.json.liquid
product-configuration-extension/package.json.liquid
product-configuration-extension/shopify.extension.toml.liquid
product-configuration-extension/shopify.ui.extension.toml.liquid
product-configuration-extension/src/ProductDetailsConfigurationExtension.liquid
product-configuration-extension/src/ProductVariantDetailsConfigurationExtension.liquid
product-configuration-extension/tsconfig.json

Part of https://github.com/Shopify/core-issues/issues/57533
Related to https://github.com/Shopify/ui-extensions/pull/1069
Adds a new template for Bundles UI Extension

Adding Product Configuration Extension template

---

admin-action/src/ActionExtension.liquid
admin-block/src/BlockExtension.liquid

This PR should be merged *after* [this change](https://github.com/Shopify/ui-extensions/pull/1132) lands in ui-extensions.

Pass target to useApi, remove differentiation for ts

---

admin-action/package.json.liquid
admin-block/package.json.liquid
checkout-extension/package.json.liquid
product-configuration-extension/package.json.liquid

These package versions aren't published yet, but I just wanted to get the PR ready to update the templates when `2023.7.0` is ready.

Update ui-extensions packages to target `2023-07`

---

checkout-extension/shopify.extension.toml.liquid

addresses https://github.com/Shopify/extensions-templates/issues/40
comments out `network_access` for checkout ui extensions by default.

remove network access by default for checkout ui extensions

---

admin-action/src/ActionExtension.liquid

- `/* Set the translation values for each supported language in the locales directory */}` is duplicated in the react segment of the action extension
- Remove duplicate comment

remove duplicate comment about translations

---

customer-account-extension/README.md.liquid
customer-account-extension/locales/en.default.json
customer-account-extension/locales/fr.json
customer-account-extension/package.json.liquid
customer-account-extension/shopify.extension.toml.liquid
customer-account-extension/src/CustomerAccountExtension.liquid
customer-account-extension/tsconfig.json

Create a temporary template for customer account ui extension specification. The extension type is `ui_extension`
[Customer account web](https://github.com/Shopify/customer-account-web) is using legacy ui-extension library. To keep the consistence, this template is using legacy ui-extension library as well. Will update once customer-account-web is updated.
There is not a way to tophat at this moment.
This template will be [behind the betaflag](https://github.com/Shopify/partners/pull/49306/files#diff-f3fac56b6301c67fdbd99e49f6bc81b8c29d63a8e0ec56728a7fd47e863e5f12R99), and will only be shown internally.

Add customer-account-extension template

---

customer-segment-template-extension/README.md.liquid
customer-segment-template-extension/locales/en.default.json
customer-segment-template-extension/locales/fr.json
customer-segment-template-extension/package.json.liquid
customer-segment-template-extension/shopify.extension.toml.liquid
customer-segment-template-extension/src/CustomerSegmentTemplate.liquid
customer-segment-template-extension/tsconfig.json

- Close https://github.com/Shopify/customer-data-platform/issues/5712
Providing code templates for the new segmentation template type we are trying to introduce.

Add segmentation templates extension

---

customer-segment-template-extension/package.json.liquid

- Close https://github.com/Shopify/customer-data-platform/issues/6049
When testing the Customer Segment Template extension generation in production, I encountered the following error: 
Bumping the react version to 18 should fix the issue as we are matching the one in ui-extensions-react.

Bump react version fixing error seen in prod

---

pos-ui-extension/package.json.liquid

Retail ui extensions is now version 1.4.0, we need to update the default version for scaffolding new extensions.
Part of https://github.com/Shopify/pos-next-react-native/issues/26781

Update pos-ui-extension version to 1.4.0

---

admin-action/shopify.extension.toml.liquid

Resolves https://github.com/Shopify/customer-data-platform/issues/5848
When creating an action extension, our new target `admin.customer-segment-details.action.render` is missing from the shopify.extension.toml file.
**Can't ship until `2023.10` version is released** - [It's been released](https://github.com/Shopify/ui-extensions/releases/tag/%40shopify%2Fui-extensions-react%402023.10.0) ✅ 
Added target to list under Customers section

Adds segment details to admin action toml

---

customer-segment-template-extension/src/CustomerSegmentTemplate.liquid

Adding missing import for useApi in the react template

Fix missing import in react template

---

admin-block/src/BlockExtension.liquid

Removes references to `summary` from the AdminBlock templates.
Related PRs: 
- https://github.com/Shopify/ui-extensions/pull/1598
- https://github.com/Shopify/ui-api-design/pull/215
- https://github.com/Shopify/shopify-dev/pull/39812

Deprecate summary on AdminBlock

---

checkout-extension/package.json.liquid
checkout-extension/shopify.extension.toml.liquid

Updates the checkout ui extension template to use the new 2024-01 API version. 
Similar to this [previous PR](https://github.com/Shopify/extensions-templates/pull/56) that did the same for version 2023-10.
This was tophatted by scaffolding a new extension and making these same changes in there, running it locally and also installing it on a shop.

Update checkout UI extension version to 2024-01

---

payments-app-extension-credit-card/shopify.extension.toml.liquid

Related issue: https://github.com/Shopify/payments-platform/issues/4378
Related project: https://docs.google.com/document/d/1Y2Ly5sw6MalZQP8w3yraQlOs8dK3UK38LVQvQz7fC_M/edit#heading=h.8coln95uazox
Related management class: https://github.com/Shopify/shopify/blob/main/components/payment_processing/payments_partners/app/models/payments_partners/payments_app_extensions/credit_card_payments_app_extension.rb
Creates an credit card payments app extension template to be used via the CLI

Create payments app extension credit card template

---

payments-app-extension-custom-onsite/shopify.extension.toml.liquid

Related issue: https://github.com/Shopify/payments-platform/issues/4381
Related project: https://docs.google.com/document/d/1Y2Ly5sw6MalZQP8w3yraQlOs8dK3UK38LVQvQz7fC_M/edit#heading=h.8coln95uazox
Related management class: [CustomOnsite management class](https://github.com/Shopify/shopify/blob/main/components/payment_processing/payments_partners/app/models/payments_partners/payments_app_extensions/custom_onsite_payments_app_extension.rb)
Creates an custom onsite payments app extension template to be used via the CLI

Create custom onsite payments app extension template

---

payments-app-extension-redeemable/shopify.extension.toml.liquid

Related issue: https://github.com/Shopify/payments-platform/issues/4382
Related project: https://docs.google.com/document/d/1Y2Ly5sw6MalZQP8w3yraQlOs8dK3UK38LVQvQz7fC_M/edit#heading=h.8coln95uazox
Related management class: [Redeemable management class](https://github.com/Shopify/shopify/blob/main/components/payment_processing/payments_partners/app/models/payments_partners/payments_app_extensions/redeemable_payments_app_extension.rb)
Creates an custom redeemable payments app extension template to be used via the CLI

Create redeemable payments app extension template

---

payments-app-extension-credit-card/shopify.extension.toml.liquid
payments-app-extension-custom-credit-card/shopify.extension.toml.liquid
payments-app-extension-custom-onsite/shopify.extension.toml.liquid
payments-app-extension-offsite/shopify.extension.toml.liquid
payments-app-extension-redeemable/shopify.extension.toml.liquid

When introducing payment app templates (like in [this PR](https://github.com/Shopify/extensions-templates/pull/78)), we expected new properties to be on the top level, and only the `target` property inside `extensions.targeting`.
Due to the nature of TOML, if a table is declared, new properties will fall under that table, even if you leave empty lines in between.
Move the target property to the end of the TOML files.

Update broken payment app templates

---

payments-app-extension-credit-card/shopify.extension.toml.liquid
payments-app-extension-custom-credit-card/shopify.extension.toml.liquid

When developers create a new payment app extension, they are required to provide an encryption certificate with today's cli schema rules. If they want to run `dev` to test their app, they would need to setup a certificate first.
Make the certificate values optional, and match the templates to the cli schemas.

Updates payment extension with valid encryption certificates

---

admin-action/locales/en.default.json.liquid
admin-action/locales/fr.json.liquid
admin-action/src/ActionExtension.liquid
admin-block/locales/en.default.json.liquid
admin-block/locales/fr.json.liquid
admin-block/src/BlockExtension.liquid

This PR uses the `TARGET` constant in the body of the extension directly (rather than getting the string from the API), updates some deprecated methods, and logs data in the action extension to be more consistent with the block example.   
- Use `TARGET` string directly in rendered jsx
- Update deprecated methods: `appendChild` -> `append` and `updateText` -> `update`
- Add `console.log` to log data in action extension

use TARGET directly, log data, and update deprecated methods

---

payments-app-extension-credit-card/shopify.extension.toml.liquid
payments-app-extension-custom-credit-card/shopify.extension.toml.liquid

We want to simplify the developer experience when developing payment apps. To do so, we would like partners to specify encryption certificates using only its fingerprint, rather than the whole certificate.
Change templates to only use the certificate fingerprint.

Updates encryption certificates to only use fingerprints

---

flow-template/shopify.extension.toml.liquid

- Adds additional context to the `require_app` setting. This should make is more clear to the author while they're setting up their template and avoid accidentally sharing to a wider audience if they didn't intend to. This information will be available in docs as well.
- Removes `allow_one_click_activate` option, we're not certain we'll allow this behaviour in the Flow UI so simply hiding for now in case we decide to reveal it in the future.
Adds brief inline comment explaining the property's behaviour.

Add inline comment explaining require_app setting

---

checkout-extension/package.json.liquid
checkout-extension/shopify.extension.toml.liquid

Now that version 2024.4.1 has been released, this updates the templates used by the CLI to use the latest 2024-04 package version.
Similar to this https://github.com/Shopify/extensions-templates/pull/85 that did the same for version `2024-01`.
This was tophatted by scaffolding a new extension and making these same changes in there, running it locally and also installing it on a shop.

Use 2024.4.x for checkout extensions

---

admin-block/shopify.extension.toml.liquid

closes https://github.com/Shopify/app-ui/issues/958
Adding the new extension targets to the toml file of of the block extension template.
- create an app
- generate an extension via my branch 
- `npm run generate extension -- --clone-url https://github.com/Shopify/extensions-templates\#jw/new-block-targets`
- inspect the toml file for new targets

add new block targets to template comment

---

payments-app-extension-credit-card/shopify.extension.toml.liquid
payments-app-extension-custom-credit-card/shopify.extension.toml.liquid
payments-app-extension-custom-onsite/shopify.extension.toml.liquid
payments-app-extension-offsite/shopify.extension.toml.liquid
payments-app-extension-redeemable/shopify.extension.toml.liquid

See issue: https://github.com/Shopify/payments-platform/issues/5407
Adding developer notes to payments extension dynamic fields (ie. `supported countries`, `supported payment methods`)
We already have notes for `api_version` &  `buyer_label_to_locale` is not part of template field as it is an optional field 

Add dev notes for payments extension dynamic fields

---

payments-app-extension-redeemable/shopify.extension.toml.liquid

This PR ensures we use [`gift-card`] as the `supported_payment_methods`

Use gift-card as supported payment method

---

flow-template/shopify.extension.toml.liquid

Previously in the TOML we populated name and description by:
`name` - extension name from terminal input when generating template extension
`description` - placeholder value "A Template that helps increase merchant productivity"
This was found to be confusing during a convergence sync as to which actually gets used when displaying to the merchant since we also have a locale folder with name and description keys.
Update name and description to use the same pattern as other extensions "t:name" and "t:description". With this the extension author will have one place to edit name and description values (in the locale folder).

fix: Update name and description in TOML to use locale values

---

flow-template/locales/en.default.json
flow-template/locales/fr.json

We only want to show pre install instructions for now.
Remove example post install note from locale

refactor: Remove post install note from locale examples

---

admin-action/shopify.extension.toml.liquid
admin-block/shopify.extension.toml.liquid
admin-print-action/shopify.extension.toml.liquid

Use handle as default name for the Print Action extension
[(Provide a link to any relevant issues AND provide a TLDR of the issue in this pull request)](https://github.com/Shopify/app-ui/issues/1272)
Update TOML files to be more clear that only a single target is supported per Admin UI extension. Also updated the template for Print extension to use the handle as the default name.

Clarify the single target limit for Admin UI extensions

---

admin-print-action/package.json.liquid

Using the `unstable` version of `ui-extensions` in the print extension breaks when a previous version is also installed (for another extension). 
Pin specific unstable version of `ui-extensions`.

Pin unstable version for print extension

---

admin-print-action/locales/en.default.json.liquid
admin-print-action/locales/fr.json.liquid
admin-print-action/shopify.extension.toml.liquid

We do not use `name` in the print extension but we can't remove it from the `toml` because we use it to validate ui-extensions.  
This PR adds a comment in the `toml` and removes the translations.

Remove name translateions and add comment in toml

---

editor-extension-collection/locales/en.default.json
editor-extension-collection/locales/fr.json

Updating the collection names of the default editor extension collection to be shorter

Update collection name for editor extension collection

---

admin-print-action/src/PrintActionExtension.liquid

Awkward wording in comment.
Fix word order in comment in print extension template.

Fix word order on comment in print action extension template

---

checkout-extension/README.md.liquid
checkout-extension/locales/en.default.json
checkout-extension/locales/fr.json
checkout-extension/package.json.liquid
checkout-extension/shopify.extension.toml.liquid
checkout-extension/src/Checkout.liquid

Part of https://github.com/Shopify/checkout-web/issues/35555
Now that [2024-07 has been released](https://shopify.dev/docs/api/checkout-ui-extensions/2024-07/instructions-update). It is important that 3p devs check for [cart instructions](https://shopify.dev/docs/api/checkout-ui-extensions/2024-07/apis/cart-instructions) before using certain APIs. Failure to do so could mean they are rendering UI extensions in certain contexts where they won't work as expected.
This updates the template used to generate the code for checkout UI extensions. Instead of simply rendering a banner as it did before, this will now render that same banner in addition to a "checkbox" to request a free gift (saved using checkout attributes). This uses **cart instructions** to check whether attributes are available. …

Update checkout UI extension template (2024-07)

---

payments-app-extension-custom-credit-card/shopify.extension.toml.liquid
payments-app-extension-custom-onsite/shopify.extension.toml.liquid
payments-app-extension-offsite/shopify.extension.toml.liquid
payments-app-extension-redeemable/shopify.extension.toml.liquid

Adds `buyer_label` and `buyer_label_translations` example values into the example templates for all payment extension types except for credit card. 
Slack thread: https://shopify.slack.com/archives/C066SQUMP16/p1720545043454769
As they're optional, commented the examples out

Add buyer label translation examples to payment extensions

---

customer-segment-template-extension/package.json.liquid
customer-segment-template-extension/shopify.extension.toml.liquid
validation-settings/package.json.liquid
validation-settings/shopify.extension.toml.liquid

These extensions are unnecessarily using the `unstable` API version, as they have each been released in a [public API version](https://shopify.dev/docs/api/admin-extensions/2024-07/extension-targets). This PR switches them to use the `2024-07` API version instead.

Update Admin UI extensions to use stable API version

---

marketing-activity/shopify.extension.toml.liquid
templates.json

Add marketing activity extension template

Add marketing activity extension template

---

discount-function-metafields-block/locales/en.default.json.liquid
discount-function-metafields-block/package.json.liquid
discount-function-metafields-block/src/BlockExtension.liquid

This matches the namespace to the tutorial and sets the applyMetafields function to the form onSave prop.
This improves stage management in admin. 
[These docs](https://shopify-dev.shopify-dev-4dcf.ian-phipps.us.spin.dev/docs/apps/build/discounts/build-ui-extension?extension=javascript) are good instructions to tophat
On step 3, be sure you're on cli version 3.66.1 `shopify --version`
and run 
```
shopify app generate extension --clone-url https://github.com/Shopify/extensions-templates\#iphipps/adjust-discount-extension --name product-discount-js-block
```
And choose the `Discount Function Metafields - UI Extension`

[Discounts] Add applyMetafields to the form onSave prop

---

customer-account-extension/package.json.liquid
customer-account-extension/shopify.extension.toml.liquid

We now have a stable version. Let's use it.

use stable version for customer-account extensions

---

order-routing-location-rule/package.json.liquid
order-routing-location-rule/shopify.extension.toml.liquid

From @vividviolet in this [slack conversation](https://shopify.slack.com/archives/C04848YTM0F/p1727804020083779):
> [...] we shouldn't have unstable in the template once the extension is made available to partners
Update default `api_version` to the latest `2024-10` version

Updates order_routing_location_rule template api_version to 2024-10

---

discount-details-function-settings-block/locales/en.default.json.liquid
discount-details-function-settings-block/src/DiscountFunctionSettings.liquid

We determined that `description` is a better name than `percentage` for this translation key.

Rename translation key from percentage to description

---

templates.json

- The new app management API that powers dev dash and the new apps platform does not offer support for app beta flags. Therefore, any extension templates gated on `appBetaFlags` will not work as such within the CLI when talking to the new APIs.
- The only reference to an `appBetaFlag` in the extensions templates config is for [this flag](https://experiments.shopify.com/flags/extensions_only_discounts_app), which is rolled out to 100% already.
- Therefore, dropping this outright should be fine. This means the template is available to everyone.
- Drop the only consumer of `appBetaFlags` from the templates file.

Remove support for appBetaFlags in extension templates configs

---

admin-link/shopify.extension.toml.liquid

Fixing spelling error in Admin Link template

---

conditional-action-extension-ts/package.json.liquid

The conditional-rendering APIs are in the unstable version. 
Modify the `ui-extensions` version in the conditional action extension template.

Use unstable version of ui-extensions

---

conditional-action-extension-js/package.json.liquid
conditional-action-extension-ts/package.json.liquid

Follow up to https://github.com/Shopify/extensions-templates/pull/184. We need a specific version of `unstable`. We also need to add it to both flavors of the template. 
Update unstable version and add to JS flavor of the template.

Fix ui-extensions versions

---

admin-action/package.json.liquid
admin-block/package.json.liquid
admin-print-action/package.json.liquid
admin-purchase-options-action/package.json.liquid
checkout-extension/package.json.liquid
conditional-action-extension-js/package.json.liquid
conditional-action-extension-ts/package.json.liquid
customer-account-extension/package.json.liquid
customer-segment-template-extension/package.json.liquid
discount-details-function-settings-block/package.json.liquid
order-routing-location-rule/package.json.liquid
pos-ui-extension/package.json.liquid
validation-settings/package.json.liquid

react-reconciler being in `devDependencies` [is causing issues](https://community.shopify.dev/t/could-not-resolve-react-reconciler/4443) when a partner generates a new extension in an app that doesn’t use workspaces.
I looked into this a bit and if an app uses workspaces, the `generate` command creates a `package.json` for each extension, masking this issue.
If an app doesn’t use workspaces, the cli adds dependencies declared in the template to the main package.json, but only `dependencies` and not `devDependencies`
I think react-reconciler should have always been part of dependencies in the first place, but perhaps I’m missing something.

move react-reconciler to dependencies

---

admin-link/shopify.extension.toml.liquid
discount-details-function-settings-block/shopify.extension.toml.liquid
support-link/shopify.extension.toml.liquid
templates.json

Part of: https://github.com/Shopify/develop-app-outer-loop/issues/1308
New extension templates that have been added since the team moved partners extension templates in https://github.com/Shopify/extensions-templates/blob/main/templates.json and some are missing the uid property.
While the user can fix this in the context of running the deploy command by deploying a second time, in the context of dev it will not have a uid in the TOML, and will therefore not be properly recognized by the App Management API.
We therefore want to make sure each template adds the uid if available.
Ensure all templates add the uid if available.
Based on https://github.com/Shopify/extensions-templates/blob/main/templates.json, the full list of template files is:
- …

1308 include uid in templates

---

admin-action/package.json.liquid
admin-block/package.json.liquid
admin-print-action/package.json.liquid
conditional-action-extension-js/package.json.liquid
conditional-action-extension-ts/package.json.liquid

We just released the [`2025.1.0`](https://www.npmjs.com/package/@shopify/ui-extensions) versions of `ui-extensions` and `ui-extensions-react`. This updates our templates to use the latest versions. 
Update versions to latest

Update ui-extensions versions in templates

---

product-configuration-extension/shopify.extension.toml.liquid

Finishes this issue: https://github.com/Shopify/bundles-app/issues/2953?issue=Shopify%7Cextensions-templates%7C197
by adding the appropriate config
Following the thread in https://github.com/Shopify/ui-api-design/pull/798#issuecomment-2602692529 with the most recent suggestions implemented

Add Extension URL Config

---

admin-action/shopify.extension.toml.liquid
admin-block/shopify.extension.toml.liquid
admin-print-action/shopify.extension.toml.liquid
conditional-action-extension-js/shopify.extension.toml.liquid
conditional-action-extension-ts/shopify.extension.toml.liquid

All admin templates should be using the latest API versions. 
Update API versions in toml files.

Update API version for all admin extensions

---

product-configuration-extension/package.json.liquid
product-configuration-extension/src/ProductDetailsConfigurationExtension.liquid
product-configuration-extension/src/ProductVariantDetailsConfigurationExtension.liquid
product-configuration-extension/tsconfig.json

This PR:
- adds graphql querying for product/variant + components (in place of the existing (& deprecated) `data.product`/`data.variant` json blob that is passed in.
- includes a bare minimal list of components
- updates dependencies

feat(products): Update product configuration extensions to include GraphQL Query sample and support React 18 and latest UI extensions

---

product-configuration-extension/shopify.extension.toml.liquid

Removes the edit url from the product variant configuration extension point as setting the url on the product variant configuration card is not yet supported.
Quick fix for small oversight in https://github.com/Shopify/extensions-templates/pull/199

Removes edit url config from product variant target point

---

admin-block/shopify.extension.toml.liquid
admin-print-action/shopify.extension.toml.liquid
admin-purchase-options-action/shopify.extension.toml.liquid
conditional-action-extension-js/shopify.extension.toml.liquid
product-configuration-extension/shopify.extension.toml.liquid

Fix malformed toml file.
- Run `REMOTE_DOM_EXPERIMENT=true shopify app generate extension --clone-url https://github.com/Shopify/extensions-templates#fix-toml` and test all of these options:
- Admin block
- Admin print action
- Admin purchase options action
- Conditional admin action
- Product configuration
- Verify the extension is generated correctly

Fix toml for remote dom extensions

---

pos-ui-extension/package.json.liquid
pos-ui-extension/shopify.extension.toml.liquid

This won't merge until 4/9 which is 100% rollout for 9.31
This updates the base template version to 2025-04 for POS UI Extensions

[DO NOT MERGE UNTIL 4/9] Update to version to 2025-04

---

checkout-extension/locales/en.default.json
checkout-extension/locales/fr.json
checkout-extension/package.json.liquid
checkout-extension/shopify.extension.toml.liquid
checkout-extension/src/Checkout.liquid
checkout-extension/tsconfig.json.liquid

Fixes https://github.com/Shopify/checkout-web/issues/44281
This updates the template for newly generated Checkout UI extensions.
Make sure `pnpm` is up to date
Use [this CLI snapshot](https://github.com/Shopify/cli/pull/5633)
```
pnpm i -g @shopify/cli@0.0.0-snapshot-20250410123718 --@shopify:registry=https://registry.npmjs.org
```
Check the version
```
% shopify --version
@shopify/cli/0.0.0-snapshot-20250410123718 darwin-arm64 node-v23.10.0
```
Create an app. Select _Remix_ and _TypeScript_.
```
shopify app init
```
Change into the app directory and generate an extension with this template
```
POLARIS_UNIFIED=true shopify app generate extension --clone-url https://github.com/Shopify/extensions-templates#km-checkout-templates   
```
Run the app
```
shopify app dev
```
Here's what it …

Update checkout UI templates for 2025-07 RC

---

customer-account-extension/package.json.liquid
customer-account-extension/shopify.extension.toml.liquid
customer-account-extension/src/OrderStatusBlock.liquid
customer-account-extension/tsconfig.json.liquid

This updates the template for newly generated customer account UI extensions.
Make sure `pnpm` is up to date
Use [this CLI snapshot](https://github.com/Shopify/cli/pull/5633)
```
pnpm i -g @shopify/cli@0.0.0-snapshot-20250410123718 --@shopify:registry=https://registry.npmjs.org
or
npm i -g @shopify/cli@0.0.0-snapshot-20250410123718 --registry=https://registry.npmjs.org
```
Check the version
```
% shopify --version
@shopify/cli/0.0.0-snapshot-20250410123718 darwin-arm64 node-v23.10.0
```
Create an app. Select _Remix_ and _TypeScript_.
```
shopify app init
```
Change into the app directory and generate an extension with this template
```
POLARIS_UNIFIED=true shopify app generate extension --clone-url https://github.com/Shopify/extensions-templates#Update-customer-account-UI-templates-for-202 …
```

Update customer account UI templates for 2025-07 RC

---

customer-account-extension/src/OrderStatusBlock.liquid

`alignment="center` is not valid. 
And while reviewing the example, there is no meaning to use Stack with alignment. Banner will have an info icon, and the icon will not center.

remove s-stack for customer account preact example

---

terminal-management/shopify.extension.toml.liquid

Part of issue https://github.com/shop/issues-retail-on-payments-platform/issues/49
RPP is no longer just enabling cloud terminals, but local terminals as well. Because of this we're renaming the extension to the more general terminal_management_extension.
Rename extension specification and relevant fields

Add terminal management extension.

---

templates.json

See [Rename cli_payment_extensions feature flag to payments_extensions #285](https://github.com/shop/issues-payment-partners/issues/285).

Rename cli_payment_extensions feature flag to payments_extensions

---

templates.json

Rename `cli_payment_extensions` feature flag to `payments_extensions` for card-present, as already done for the other payment extensions with https://github.com/Shopify/extensions-templates/pull/241. Card-present was added to this repo concomitantly with 
- https://github.com/Shopify/extensions-templates/pull/241 
by 
- https://github.com/Shopify/extensions-templates/pull/236
Part of https://github.com/shop/issues-payment-partners/issues/285.

Rename cli_payment_extensions feature flag to payments_extensions for card-present

---

admin-block/src/BlockExtension.liquid
admin-purchase-options-action/src/PurchaseOptionsActionExtension.liquid

- Changed the `title` prop to `heading` in the `AdminBlock` component to align with the correct API
- Updated event handlers in form elements to use `event.currentTarget` instead to get proper typing

Fix type issues in Admin preact templates

---

functions-cart-checkout-validation-js/package.json.liquid
functions-cart-transform-js/package.json.liquid
functions-delivery-customization-js/package.json.liquid
functions-discount-js/package.json.liquid
functions-discounts-allocator-js/package.json.liquid
functions-fulfillment-constraints-js/package.json.liquid
functions-local-pickup-delivery-option-generators-js/package.json.liquid
functions-location-rules-js/package.json.liquid
functions-order-discounts-js/package.json.liquid
functions-payment-customization-js/package.json.liquid
functions-pickup-point-delivery-option-generators-js/package.json.liquid
functions-pickup-point-delivery-option-generators-ts/package.json.liquid
functions-product-discounts-js/package.json.liquid
functions-shipping-discounts-js/package.json.liquid

Vitest 3.1.3 uses [Vite 6+](https://github.com/vitest-dev/vitest/blob/6e8d9377949b78957a2a617b922925250c80fbcb/package.json#L66), which in turn [does not support node 21](https://github.com/vitejs/vite/blob/5fdcfe77a93ca7bc90a5427a2a20eceaee1c4da1/package.json#L5-L7).
The CLI [currently supports node 21](https://shopify.dev/docs/api/shopify-cli#requirements), so our templates need to work on that version.
Downgrades vitest dep in our function js templates to v2.
Did a find and replace of ` "vitest": "^3.1.3"` -> `"vitest": "2.1.9"` in all `package.json.liquid` files.
Ran `npm install` within my function directory with various versions of `node` and the `vitest` dep.

downgrade js function vitest dependency to support node 21

---

admin-action/src/ActionExtension.liquid
admin-purchase-options-action/src/PurchaseOptionsActionExtension.liquid
conditional-action-extension-js/src/ActionExtension.liquid

The `ui-extensions` have been updated to use kebab case.
This PR updates the templates to follow the new casing convention.

Update templates to use kebab case slot names

---

templates.json

We're moving our Function templates from `function-examples` to `extensions-templates`
Update the `templates.json` to point to the right repo/path

Point to `extensions-templates` in `templates.json`

---

checkout-extension/src/Checkout.liquid

We have decided ([internal decision](https://docs.google.com/document/d/1Asx-neu8JgEnCeB_Z7lbk61PLydA56YxHrwpzP6EzzQ/edit?tab=t.0#heading=h.nyyxyhny0fzo)) to support Preact signals via side-effect import. It's not implemented yet but I'd like to add this to the template so that extensions are more likely to include the import. It won't do any harm.
Future proof extensions created from the template.
Make sure `pnpm` is `10.9.0` or higher
Use the latest CLI
```
pnpm i -g @shopify/cli@latest --@shopify:registry=https://registry.npmjs.org
```
Check the version
```
shopify --version                                                           
@shopify/cli/3.80.3 darwin-arm64 node-v23.10.0
```
Create an app. Select _Remix_ and _TypeScript_.
```
shopify app init
```
Change into the app directory …

Apply Preact side effect for future-proofing

---

templates.json

The shopify CLI filters which payment extension can be created by a developer based on feature flags. The CLI load `templates.json` at run time, to load which organizational feature flags apply to a given extension.
In `templates.json`, we presently gate all the payments extensions being the `payments_extensions` feature flag.
Each payments extension type has its own specific organizational feature flag that will be checked by plugins in `core`, to prevent that an extension is deployed if the feature flag is not enabled. These specific flags have been introduced by https://github.com/Shopify/business-platform/pull/26938. The offsite payment extension is an exception and it is not gated by a specific feature flag, because it is not gated today, before the migration to the business …

Add individual payments extensions feature flags

---

pos-ui-extension-customer-details/package.json.liquid
pos-ui-extension-customer-details/shopify.extension.toml.liquid
pos-ui-extension-customer-details/src/Action.liquid
pos-ui-extension-customer-details/src/Block.liquid
pos-ui-extension-customer-details/src/MenuItem.liquid
templates.json

Add customer details template
Tophat
1. Go to cli
2. `pnpm shopify app generate extension --clone-url="https://github.com/Shopify/extensions-templates#andy-chhuon/60654-add-pos-ui-templates" --path ./your-app-root`
If the above doesn't work (can't see template in input list), replace `extensionTemplates` in `packages/app/src/cli/services/generate.ts` [L43](https://github.com/Shopify/cli/blob/main/packages/app/src/cli/services/generate.ts#L43) with
```js
const extensionTemplates = await fetch(
'https://raw.githubusercontent.com/Shopify/extensions-templates/refs/heads/andy-chhuon/60654-add-pos-ui-templates/templates.json?cache_bust=fdsfsdsf',
)
.then((res) => res.json())
.then((data) => data as ExtensionTemplate[])
``` …

60654: add customer details template

---

templates.json

Make Shopyfolks and 3P developers life easier by having feature flags behave the same across all payments extensions.
1. No more "global" payment program membership that also gives access to offsite extensions only
1. One-to-one correspondence between payments extensions and feature flags
Rename `payments_extensions` as `payments_extensions_offsite`

Repurpose and rename payments_extensions as payments_extensions_offsite

---

templates.json

The paths for various JavaScript and TypeScript templates in the templates.json file are incorrect, pointing to "admin-action" when they should be pointing to different locations.

Fix remote ui template paths

---

pos-ui-extension-order-details/package.json.liquid
pos-ui-extension-order-details/shopify.extension.toml.liquid
pos-ui-extension-order-details/src/Action.liquid
pos-ui-extension-order-details/src/Block.liquid
pos-ui-extension-order-details/src/MenuItem.liquid
templates.json

Add order details template
Tophat
1. Go to cli
2. pnpm shopify app generate extension --clone-url="https://github.com/Shopify/extensions-templates#andy-chhuon/60654-add-pos-ui-order-details" --path ./your-app-root
If the above doesn't work (can't see template in input list), replace extensionTemplates in packages/app/src/cli/services/generate.ts with
const extensionTemplates = await fetch(
'https://raw.githubusercontent.com/Shopify/extensions-templates/refs/heads/andy-chhuon/60654-add-pos-ui-order-details/templates.json?cache_bust=fdsfsdsf',
)
.then((res) => res.json())
.then((data) => data as ExtensionTemplate[])
Tophat screencapture:
https://share.descript.com/view/WBUBspKHpTP

60654: Add order details template

---

pos-ui-extension-post-purchase/package.json.liquid
pos-ui-extension-post-purchase/shopify.extension.toml.liquid
pos-ui-extension-post-purchase/src/Action.liquid
pos-ui-extension-post-purchase/src/Block.liquid
pos-ui-extension-post-purchase/src/MenuItem.liquid
templates.json

Add post purchase template
Tophat
1. Go to cli
2. pnpm shopify app generate extension --clone-url="https://github.com/Shopify/extensions-templates#andy-chhuon/60654-add-pos-ui-post-purchase-template" --path ./your-app-root
If the above doesn't work (can't see template in input list), replace extensionTemplates in packages/app/src/cli/services/generate.ts with
const extensionTemplates = await fetch(
'https://raw.githubusercontent.com/Shopify/extensions-templates/refs/heads/andy-chhuon/60654-add-pos-ui-post-purchase-template/templates.json?cache_bust=fdsfsddsf',
)
.then((res) => res.json())
.then((data) => data as ExtensionTemplate[])
Tophat screencapture:
https://share.descript.com/view/SBq2IzRsJNd

60654: Add post purchase template

---

pos-ui-extension-draft-order-details/package.json.liquid
pos-ui-extension-draft-order-details/shopify.extension.toml.liquid
pos-ui-extension-draft-order-details/src/Action.liquid
pos-ui-extension-draft-order-details/src/Block.liquid
pos-ui-extension-draft-order-details/src/MenuItem.liquid
templates.json

Add draft orders template
Note: pos.draft-order-details.block.render seems to have the wrong AllowedComponents type (ActionComponents instead of BlockComponents)
Fixed in https://github.com/Shopify/ui-extensions/pull/2897. Switch ui-extensions to `0.0.0-snapshot-20250520192734` when tophatting to avoid typing issues in this pr.
Tophat
1. Go to cli
2. `pnpm shopify app generate extension --clone-url="https://github.com/Shopify/extensions-templates#andy-chhuon/60654-add-pos-ui-draft-orders-template" --path ./your-app-root`
If the above doesn't work (can't see template in input list), replace `extensionTemplates` in `packages/app/src/cli/services/generate.ts` [L43](https://github.com/Shopify/cli/blob/main/packages/app/sr …

60654: Add draft orders template

---

pos-ui-extension-smart-grid/package.json.liquid
pos-ui-extension-smart-grid/shopify.extension.toml.liquid
pos-ui-extension-smart-grid/src/Modal.liquid
pos-ui-extension-smart-grid/src/Tile.liquid
templates.json

Rename pos ui smart grid
Tophat
1. Go to cli
2. `pnpm shopify app generate extension --clone-url="https://github.com/Shopify/extensions-templates#andy-chhuon/60654-rename-pos-ui-smartgrid" --path ./your-app-root`
If the above doesn't work (can't see template in input list), replace `extensionTemplates` in `packages/app/src/cli/services/generate.ts` [L43](https://github.com/Shopify/cli/blob/main/packages/app/src/cli/services/generate.ts#L43) with
```js
const extensionTemplates = await fetch(
'https://raw.githubusercontent.com/Shopify/extensions-templates/refs/heads/andy-chhuon/60654-rename-pos-ui-smartgrid/templates.json?cache_bust=fdsfsdsf',
)
.then((res) => res.json())
.then((data) => data as ExtensionTemplate[]) …
```

60654: rename pos ui smart grid

---

functions-cart-checkout-validation-rs/Cargo.toml.liquid
functions-cart-transform-rs/Cargo.toml.liquid
functions-delivery-customization-rs/Cargo.toml.liquid
functions-discount-rs/Cargo.toml.liquid
functions-discounts-allocator-rs/Cargo.toml.liquid
functions-fulfillment-constraints-rs/Cargo.toml.liquid
functions-local-pickup-delivery-option-generators-rs/Cargo.toml.liquid
functions-location-rules-rs/Cargo.toml.liquid
functions-order-discounts-rs/Cargo.toml.liquid
functions-payment-customization-rs/Cargo.toml.liquid
functions-pickup-point-delivery-option-generators-rs/Cargo.toml.liquid
functions-product-discounts-rs/Cargo.toml.liquid
functions-shipping-discounts-rs/Cargo.toml.liquid

We released a new version of `shopify_function` Rust crate with some new functionality and bug fixes.
Update the templates to use the new version.

Bump `shopify_function` Rust crate to `1.1.0`

---

product-configuration-extension/README.md

Updated the documentation link for Product Configuration extensions to reflect the new path in the developer documentation.
The PR updates the link in the README.md file to point to the correct location in Shopify's developer documentation. The new URL (`https://shopify.dev/docs/apps/build/product-merchandising/bundles/product-configuration-extension/add-merchant-config-ui`) replaces the outdated one (`https://shopify.dev/docs/apps/selling-strategies/bundles/product-config`), ensuring developers are directed to the most current documentation.
Also removed an extra space at the end of the line above the link for consistent formatting.

Update Link to Product Configuration Extension Documentation in Template

---

checkout-extension/package.json.liquid
checkout-extension/shopify.extension.toml.liquid

ui-extensions 2025-07 version release as latest stable, updating cli templates to match this new stable version
Make sure `pnpm` is `10.9.0` or higher
Use the latest CLI
```
pnpm i -g @shopify/cli@latest --@shopify:registry=https://registry.npmjs.org
```
Create an app. Select _Remix_ and _TypeScript_.
```
shopify app init
```
Change into the app directory and generate a _Checkout UI_ extension with this template
```
shopify app generate extension --clone-url https://github.com/Shopify/extensions-templates#07-03-update_checkout_cli_templates_with_2025-07_stable_version
```
When prompted, create a react/typescript extension and ensure package.json of extension references `2025.7.x` for ui-extensions and ui-extensions-react
and that extensions toml file reference `2025-07` as api version
I …

update checkout cli templates with 2025-07 stable version

---

functions-pickup-point-delivery-option-generators-rs/src/fetch.rs
functions-pickup-point-delivery-option-generators-rs/src/run.rs

CI seems to be failing on main.
`cargo clippy -- -D warnings`
```
error: variables can be used directly in the `format!` string
--> functions-pickup-point-delivery-option-generators-rs/src/fetch.rs:25:15
|
25 |       let url = format!(
|  _______________^
26 | |         "https://cdn.shopify.com/s/files/1/0628/3830/9033/files/pickup-points-external-api-v2.json?v=1714588690&lat={}&lon={}",
27 | |         latitude, longitude
28 | |     );
| |_____^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#uninlined_format_args
= note: `-D clippy::uninlined-format-args` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(clippy::uninlined_format_args)]`
error: variables can be used directly in the `format!` string
--> …
```

Fix rs format macro errors

---

.github/scripts/expand-liquid.js
.github/workflows/validate-wasm-functions.yml
README.md

There was no way to expand `wasm` example liquid files.
Add support to `yarn expand-liquid wasm`
It's not quite doing anything else than that for now (no actual CI steps) but it's a start toward parity of `wasm` with the rest.

Expand liquid wasm support

---

pos-ui-extension-customer-details/package.json.liquid
pos-ui-extension-customer-details/shopify.extension.toml.liquid
pos-ui-extension-draft-order-details/package.json.liquid
pos-ui-extension-draft-order-details/shopify.extension.toml.liquid
pos-ui-extension-order-details/package.json.liquid
pos-ui-extension-order-details/shopify.extension.toml.liquid
pos-ui-extension-post-purchase/package.json.liquid
pos-ui-extension-post-purchase/shopify.extension.toml.liquid
pos-ui-extension-product-details/package.json.liquid
pos-ui-extension-product-details/shopify.extension.toml.liquid
pos-ui-extension-smart-grid/package.json.liquid
pos-ui-extension-smart-grid/shopify.extension.toml.liquid

Related to https://github.com/shop/issues-retail/issues/1907
Updating all POS UI extensions to use the latest API version (2025-07) and corresponding dependency versions.
This PR updates all POS UI extension templates to use the 2025-07 API version instead of 2025-04. The changes include:
- Updated `api_version` from "2025-04" to "2025-07" in all `shopify.extension.toml.liquid` files
- Updated `@shopify/ui-extensions` and `@shopify/ui-extensions-react` dependencies from "2025.4.x" to "2025.7.x" in all `package.json.liquid` files
These updates ensure that all POS UI extensions use the latest available API version and corresponding dependencies.

Update POS UI Extensions for 2025-07

---

README.md

There is a github action which needs running, in order to publish the new `templates.json` to shopify cdn. That step is usually missed.
Link the Vault page to the repo.

update readme to link to guide

---

templates.json

Address [issue](https://docs.google.com/document/d/1XX6QnS6kKZTT1shcCZVcso74VWn-Ui4V2IASenHHi1E/edit?disco=AAABnidRKB4) with the `--template` argument not working for the Dev Dash.
Rename legacy templates to use the `_legacy` suffix and remove the `_preact` suffix from new templates.
1. Use a local version of the CLI and update the template url to `const TEMPLATE_JSON_URL = 'https://raw.githubusercontent.com/Shopify/extensions-templates/d7b0449124ce8933a6836c51ab47eb05eeeda7fc/templates.json'`
2. Run `pnpm shopify app generate extension --template=admin_action` and verify that it succeeds
3. Verify that using `POLARIS_UNIFIED=true pnpm shopify app generate extension --template=admin_action` also works

Rename Preact identifiers to be primary and legacy ones to have _legacy suffix

---

admin-purchase-options-action/src/ProductExtension.liquid
admin-purchase-options-action/src/ProductVariantExtension.liquid

This PR addresses an issue with file imports in the `ProductExtension.liquid` file, where JSX files weren't being properly referenced with their extensions.
Updated the import statements in `ProductExtension.liquid` to correctly reference JSX files with their `.jsx` extension. This change ensures proper file resolution during build and runtime.
Specifically:
- Changed the flavor check from `contains "preact"` to an exact match `== "preact"`
- Added the `.jsx` extension to the Preact import
- Added conditional logic for React imports to use `.jsx` extension when the flavor is exactly "react"
These changes ensure consistent file resolution across different flavor configurations.
1. Create an preact extension with the following command `POLARIS_UNIFIED=true shopify app generate extension …

Fix import paths for JSX files in ProductExtension.liquid

---

channel-config/shopify.extension.toml.liquid

Removed the `specifications` field from the Shopify extension configuration template as it can easily inferred by the specifications folder content

Remove channel specifications from channel-config extension

---

admin-purchase-options-action/src/PurchaseOptionsActionExtension.liquid
validation-settings/src/ValidationSettings.liquid

Fix type issues
- Updated event handling to use `event.currentTarget.value` instead of `event.target.value` for accessing form field values.
- Changed the initial state values for frequency and discount from numbers to strings in PurchaseOptionsActionExtension to reflect the expected value for s-number-field
- Updated the function settings component to properly use `onSubmit` event with `waitUntil` instead of `onSave`

Fix type issues by using event.currentTarget instead of event.target

---

customer-segment-template-data-extension/tsconfig.json.liquid
discount-details-function-settings-block/package.json.liquid
discount-details-function-settings-block/shopify.extension.toml.liquid
discount-details-function-settings-block/src/DiscountFunctionSettings.liquid
discount-details-function-settings-block/tsconfig.json.liquid
order-routing-location-rule/src/OrderRoutingLocationRule.liquid
templates.json

Add preact support for DiscountFunctionSettings and OrderRoutingLocationRule templates
1. Checkout this PR on the CLI https://github.com/Shopify/cli/pull/6421
2. In the CLI repo, open `packages/cli-kit/src/public/common/version.ts` and update `CLI_KIT_VERSION`
```ts
export const CLI_KIT_VERSION = '3.85.1'
```
3. In the CLI repo, open `packages/app/src/cli/utilities/developer-platform-client/app-management-client.ts` and update `TEMPLATE_JSON_URL`
```ts
const TEMPLATE_JSON_URL =
'https://raw.githubusercontent.com/Shopify/extensions-templates/refs/heads/Add_preact_support_for_DiscountFunctionSettings_and_OrderRoutingLocationRule_templates/templates.json'
```
4. In the CLI repo run `pnpm shopify app generate extension --clone-url https://github.com/Shopify/extensions-templates#Add_preact_supp …

Add preact support for DiscountFunctionSettings and OrderRoutingLocationRule templates

---

discount-details-function-settings-block/src/DiscountFunctionSettings.liquid

Howdy!
I was putting together a demo this morning and ran into a few bugs after generating a new extension-only app with a discount function + Discount function settings ui (CLI `3.85.4`)
- infinite `useEffect` render loop
- select menu not working
Both quick fixes that I've already tested for the demo, dropping them here in case it hasn't been flagged yet.
- infinite render is resolve by apply `useMemo` (same dependency as react template)
- updated select menu to use <s-option> from polaris web components

Preact discount settings bug fixes
