Shopify/extensions-templates

flow_action/shopify.extension.toml.liquid
flow_trigger/shopify.extension.toml.liquid

Templates needed updating to match our CLI templates.
- Moved `description` to extensions.
- Updated trigger field `key` to sentence case.

Updated flow extensions

---

admin-action/src/ActionExtension.liquid
admin-block/src/BlockExtension.liquid

Extract target into a const

---

customer-segment-template-extension/src/CustomerSegmentTemplate.liquid

Updating prop names to match the new public API

[CustomerSegmentTemplate] Change extension template prop names

---

customer-account-extension/package.json.liquid
customer-account-extension/src/CustomerAccountExtension.liquid

Change customer account template:
1. ui extension package
2. Import new package

Update packages in customer account template

---

flow-template/shopify.extension.toml.liquid

Just a tweak since fraud isn't a valid category
Replaces with `risk`

Remove fraud category and replace with risk

---

product-configuration-extension/README.md.liquid

Fix link in readme

---

customer-account-extension/README.md.liquid

Fix: update customer account name

---

.gitignore
admin-action/package.json.liquid
admin-action/shopify.extension.toml.liquid
admin-block/package.json.liquid
admin-block/shopify.extension.toml.liquid

Update admin templates to use latest version

---

payments-app-extension-credit-card/shopify.extension.toml.liquid
payments-app-extension-custom-credit-card/shopify.extension.toml.liquid
payments-app-extension-custom-onsite/shopify.extension.toml.liquid
payments-app-extension-offsite/shopify.extension.toml.liquid
payments-app-extension-redeemable/shopify.extension.toml.liquid

Changes include:
- Use latest api_version
- Add UI Extension commented code in onsite & custom CC
See description

Payment app TOML file enhancements

---

admin-print-action/locales/en.default.json.liquid
admin-print-action/locales/fr.json.liquid
admin-print-action/shopify.extension.toml.liquid
admin-print-action/src/PrintActionExtension.liquid

Gets print extension template into a more final state. There will still be some work to remove the name. 
Match designs.

Update print action template

---

admin-print-action/src/PrintActionExtension.liquid

Switch the checkbox name properties to be the right values.

Switch checkbox name properties

---

admin-print-action/shopify.extension.toml.liquid

Fix missing name in the TOML for print action extension

---

admin-action/shopify.extension.toml.liquid
admin-block/shopify.extension.toml.liquid

- https://github.com/Shopify/app-ui/issues/1449
Add new targets to the template .toml file

New Action/Block targets: Company, Catalog, Gift card

---

discount-function-metafields-block/src/BlockExtension.liquid

Updating the order of nesting between form and function settings.

fix discount example

---

pos-ui-extension/package.json.liquid
pos-ui-extension/shopify.extension.toml.liquid

Resolves https://github.com/Shopify/pos-next-react-native/issues/43130
Update the pos-ui-extension template for 2024-10

Rework pos-ui-extension template for 2024-10

---

discount-details-function-settings-block/locales/en.default.json.liquid
discount-details-function-settings-block/shopify.extension.toml.liquid
discount-details-function-settings-block/src/DiscountFunctionSettings.liquid

Updating file names and removing locales.

Update file name

---

discount-details-function-settings-block/package.json.liquid
discount-details-function-settings-block/shopify.extension.toml.liquid

fix discount toml

---

conditional-admin-action/README.md.liquid
conditional-admin-action/package.json.liquid
conditional-admin-action/shopify.extension.toml.liquid
conditional-admin-action/src/ActionExtension.liquid
conditional-admin-action/src/ShouldRender.liquid

Add template for data extension

---

admin-link/README.md.liquid
admin-link/locales/en.default.json.liquid
admin-link/shopify.extension.toml.liquid

Add some documentation and clean translation files
Add some documentation and clean translation files

include get support in docs and removed comma from locales

---

conditional-action-extension/shopify.extension.toml.liquid
conditional-action-extension/src/ShouldRender.liquid

Updating the template to use `should-render` targets

Update conditional-action-extension template

---

admin-link/shopify.extension.toml.liquid

current url description is ambiguous
Add better description of valid link url values

url instructions more specific to app type

---

templates.json

The templates JSON has fallen behind. This brings it up to speed.
Update `templates.json`

Update templates list to match current state for Partners

---

conditional-action-extension-ts/locales/en.default.json.liquid
conditional-action-extension-ts/locales/fr.json.liquid

Fix test locales in conditional action extension

---

admin-action/tsconfig.json.liquid
admin-block/tsconfig.json.liquid
admin-print-action/tsconfig.json.liquid
admin-purchase-options-action/tsconfig.json.liquid
checkout-extension/tsconfig.json.liquid
conditional-action-extension-js/tsconfig.json.liquid
customer-account-extension/tsconfig.json.liquid
order-routing-location-rule/package.json.liquid
order-routing-location-rule/shopify.extension.toml.liquid
product-configuration-extension/tsconfig.json.liquid

Fix https://github.com/Shopify/app-ui/issues/2208

Remove include: [./src] from tsconfig so shopify.d.ts can be picked up

---

conditional-action-extension-js/src/condition/shouldRender.js.liquid

Fix issue with missing line break

Fix missing line break in conditional action extension template

---

admin-action/shopify.extension.toml.liquid
admin-block/shopify.extension.toml.liquid
admin-print-action/shopify.extension.toml.liquid
admin-purchase-options-action/shopify.extension.toml.liquid
checkout-extension/shopify.extension.toml.liquid
conditional-action-extension-js/shopify.extension.toml.liquid
customer-account-extension/shopify.extension.toml.liquid
product-configuration-extension/shopify.extension.toml.liquid

Use 2025-10 for preact templates

---

admin-block/src/BlockExtension.liquid
admin-print-action/src/PrintActionExtension.liquid

Update title / heading props for admin action and banner

---

customer-account-extension/package.json.liquid
customer-account-extension/shopify.extension.toml.liquid

Updates the API version and dependencies for the customer account extension template.

bump version to 2025-07 for customer account

---

pos-ui-extension-cart-line-item-details/package.json.liquid
pos-ui-extension-cart-line-item-details/shopify.extension.toml.liquid
pos-ui-extension-cart-line-item-details/src/Action.liquid
pos-ui-extension-cart-line-item-details/src/MenuItem.liquid
templates.json

https://github.com/shop/issues-retail/issues/15709
The solution follows the best practices.

add initial cart line item template

---

discount-details-function-settings-block/shopify.extension.toml.liquid

Updating the discount extension template to use 2025-01.

Update api version for extension

---

customer-account-extension/package.json.liquid
customer-account-extension/src/OrderStatusBlock.liquid

Closes https://github.com/shop/issues-checkout/issues/7625
Need to update the Customer account extension template to include the latest changes
- Includes the side-effect import to support Preact signals
- Updates the export to be an async anon function
- Adds @preact/signals as a direct dependency
1. Generate a _Customer account UI_ extension with this template
```
POLARIS_UNIFIED=true shopify app generate extension --clone-url https://github.com/Shopify/extensions-templates#lsit/update-ca-template
```
2. Run the app
```
shopify app dev
```
Here's what it should look like
<details>
<summary>📸 Screenshot</summary>
</details>
3. Verify that the generated code to has the changes were applied

Update Customer account extension template
